
on:
  workflow_dispatch:
    inputs:
      repositories:
        description: 'Repositories (default: "", example: ["transmissions11/solmate"])'
        required: false
        type: string
        default: ''
      runners:
        description: 'Runs-on (default: ["ubuntu-latest"])'
        required: true
        type: string
        default: '["ubuntu-latest"]'
      hardhat-version:
        description: 'Hardhat version (default: "3.0.0-next.19")'
        required: true
        type: string
        default: '3.0.0-next.19'
      build-dependencies:
        description: 'Hardhat build dependencies (default: "", example: ["hardhat-utils"])'
        required: false
        type: string
        default: ''
      forge-version:
        description: 'Forge version (default: "v0.3.0")'
        required: true
        type: string
        default: 'v0.3.0'
      node-version:
        description: 'Node.js version (default: "22.10.0")'
        required: true
        type: string
        default: '22.10.0'

defaults:
  run:
    shell: bash

env:
  HARDHAT_VERSION: ${{ github.event.inputs.hardhat-version }}
  FORGE_VERSION: ${{ github.event.inputs.forge-version }}
  NODE_VERSION: ${{ github.event.inputs.node-version }}

jobs:
  discover:
    if: github.event.inputs.repositories == ''
    runs-on: ubuntu-latest
    outputs:
      repositories: ${{ steps.repositories.outputs.repositories }}
    steps:
      - name: Checkout the testing repository
        uses: actions/checkout@v4
      - name: Find repositories that need to be tested
        id: repositories
        run: |
          echo "repositories<<EOF" >> $GITHUB_OUTPUT
          jq -r 'keys' repositories.json | tee -a $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
  build:
    if: (!startsWith(github.event.inputs.hardhat-version, '3.0.0'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Hardhat repository
        uses: actions/checkout@v4
        with:
          repository: NomicFoundation/hardhat
          ref: ${{ github.event.inputs.hardhat-version }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: 22
      - name: Install dependencies
        env:
          DEPENDENCIES: ${{ github.event.inputs.build-dependencies || '[]' }}
        run: |
          pushd hardhat
            pnpm install --frozen-lockfile --prefer-offline
          popd
          for dependency in $(jq -r '.[]' <<< "$DEPENDENCIES"); do
            pushd $dependency
              pnpm install --frozen-lockfile --prefer-offline
              pnpm build
              pnpm pack
            popd
            pushd hardhat
              pnpm install ../$dependency/*.tgz
            popd
          done
        working-directory: v-next
      - name: Build the Hardhat package
        run: pnpm build
        working-directory: v-next/hardhat
      - name: Pack the Hardhat package
        run: pnpm pack
        working-directory: v-next/hardhat
      - name: Upload the Hardhat package
        uses: actions/upload-artifact@v4
        with:
          name: hardhat
          path: v-next/*/*.tgz
  run:
    if: (!cancelled())
    needs:
      - discover
      - build
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ github.event.inputs.repositories != '' && fromJson(github.event.inputs.repositories) || fromJson(needs.discover.outputs.repositories) }}
        runner: ${{ fromJson(github.event.inputs.runners) }}
        run:
          - command: forge build
            regex: 'Compiling [0-9]+ files with Solc [0-9]+\.[0-9]+'
          - command: forge test
            regex: 'Ran [0-9]+ test suites in [0-9]+\.[0-9]+m?s \([0-9]+\.[0-9]+m?s CPU time\): [0-9]+ tests passed, [0-9]+ failed, [0-9]+ skipped \([0-9]+ total tests\)'
          - command: hardhat compile
            regex: 'Compiled [0-9]+ Solidity files with solc [0-9]+\.[0-9]+'
          - command: hardhat test solidity
            regex: 'Run (Failed|Passed): [0-9]+ tests, [0-9]+ passed, [0-9]+ failed, [0-9]+ skipped \(duration: [0-9]+ ms\)'
    steps:
      - name: Checkout the testing repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.repository }}
      - name: Find the configuration for the repository
        id: config
        env:
          REPOSITORY: ${{ matrix.repository }}
        run: |
          echo "config<<EOF" >> $GITHUB_OUTPUT
          jq -r '.[env.REPOSITORY]' repositories.json | tee -a $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        working-directory: ${{ github.repository }}
      - name: Checkout the repository to be tested
        id: repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: ${{ matrix.repository }}
          path: ${{ matrix.repository }}
          ref: ${{ fromJSON(steps.config.outputs.config).ref }}
      - name: Remove ignored paths
        if: fromJSON(steps.config.outputs.config).ignore != ''
        env:
          IGNORE: ${{ toJSON(fromJSON(steps.config.outputs.config).ignore) }}
        run: |
          for path in $(jq -r 'keys' <<< "$IGNORE"); do
            rm -rf "${path}"
          done
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c
        with:
          version: ${{ env.FORGE_VERSION }}
          cache: false
      - name: Install Hardhat
        if: startsWith(github.event.inputs.hardhat-version, '3.0.0')
        run: npm install -g @ignored/hardhat-vnext@${{ env.HARDHAT_VERSION }}
      - name: Download Hardhat
        if: (!startsWith(github.event.inputs.hardhat-version, '3.0.0'))
        uses: actions/download-artifact@v4
        with:
          name: hardhat
      - name: Install Hardhat
        if: (!startsWith(github.event.inputs.hardhat-version, '3.0.0'))
        run: npm install -g *.tgz
        working-directory: hardhat
      - name: Install the package manager
        if: fromJSON(steps.config.outputs.config).packageManager != '' && fromJSON(steps.config.outputs.config).packageManager != 'npm'
        run: npm install -g ${{ fromJSON(steps.config.outputs.config).packageManager }}
      - name: Install the dependencies
        if: fromJSON(steps.config.outputs.config).packageManager != ''
        run: ${{ fromJSON(steps.config.outputs.config).packageManager }} install
        working-directory: ${{ matrix.repository }}
      - name: Initialize the repository
        if: fromJSON(steps.config.outputs.config).packageManager == ''
        run: npm init -y
        working-directory: ${{ matrix.repository }}
      - name: Set the package type
        run: npm pkg set type="module"
        working-directory: ${{ matrix.repository }}
      - name: Set the Hardhat configuration
        env:
          HARDHAT_CONFIG: ${{ toJSON(fromJSON(steps.config.outputs.config).hardhatConfig) }}
        run: |
          rm hardhat.config.ts 2>/dev/null || true
          echo "export default $HARDHAT_CONFIG;" > hardhat.config.js
          sed -i 's/blockGasLimit": "\([0-9]\+\)"/blockGasLimit": BigInt(\1)/' hardhat.config.js
          sed -i 's/blockTimestamp": "\([0-9]\+\)"/blockTimestamp": BigInt(\1)/' hardhat.config.js
          cat hardhat.config.js
        working-directory: ${{ matrix.repository }}
      - name: Run ${{ matrix.run.command }}
        id: run
        env:
          CONFIG_ENV: ${{ toJSON(fromJSON(steps.config.outputs.config).env || fromJSON('{}')) }}
          DEBUG: ${{ runner.debug && '*' || '' }}
        run: |
          for key in $(jq -r 'keys[]' <<< "$CONFIG_ENV"); do
            value=$(jq -r ".[\"$key\"]" <<< "$CONFIG_ENV")
            export "$key"="$value"
          done
          if [[ -f /usr/bin/time ]]; then
            /usr/bin/time -o '${{ matrix.run.command }}.time' -p ${{ matrix.run.command }} 2>&1 | tee -a '${{ matrix.run.command }}.out'
          else
            before=$(date +%s)
            { ${{ matrix.run.command }} 2>&1 || exit_code=$?; } | tee -a '${{ matrix.run.command }}.out'
            exit_code=${exit_code:-0}
            after=$(date +%s)
            echo "real $((after - before))" > '${{ matrix.run.command }}.time'
            exit $exit_code
          fi
        working-directory: ${{ matrix.repository }}
        continue-on-error: true
      - name: Prepare the upload
        id: upload
        env:
          REPOSITORY: ${{ matrix.repository }}
        run: |
          echo "name=${REPOSITORY%/*} ${REPOSITORY#*/} ${{ matrix.run.command }} ${{ matrix.runner }}" | tee -a $GITHUB_OUTPUT
          echo "title=${{ matrix.repository }}: ${{ matrix.run.command }} (${{ steps.run.outcome }}) [${{ matrix.runner }}]" | tee -a $GITHUB_OUTPUT
          echo "path=${{ matrix.repository }}/${{ matrix.run.command }}.result" | tee -a $GITHUB_OUTPUT
          echo "#### ${{ matrix.repository }} ($(git rev-parse --short HEAD)): ${{ matrix.run.command }} (${{ steps.run.outcome }}) [${{ matrix.runner }}]" | tee -a '${{ matrix.run.command }}.result'
          echo "" | tee -a '${{ matrix.run.command }}.result'
          echo "content<<EOF" | tee -a $GITHUB_OUTPUT
          (grep -E '${{ matrix.run.regex }}' '${{ matrix.run.command }}.out' || echo "Unexpected Error") | tee -a '${{ matrix.run.command }}.result' | tee -a $GITHUB_OUTPUT
          echo "EOF" | tee -a $GITHUB_OUTPUT
          echo "" | tee -a '${{ matrix.run.command }}.result'
          echo '${{ steps.run.outcome }}' | tee -a '${{ matrix.run.command }}.result'
          echo "" | tee -a '${{ matrix.run.command }}.result'
          cat '${{ matrix.run.command }}.time' | tee -a '${{ matrix.run.command }}.result'
        working-directory: ${{ matrix.repository }}
      - name: Set the notice
        run: |
          echo "::notice title=${{ steps.upload.outputs.title }}::${{ steps.upload.outputs.content }}"
        working-directory: ${{ matrix.repository }}
      - name: Upload the result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.upload.outputs.name }}
          path: ${{ steps.upload.outputs.path }}
  summary:
    if: (!cancelled())
    needs: run
    runs-on: ubuntu-latest
    steps:
      - name: Download the results
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
      - name: Summarize the results
        id: summary
        run: |
          echo "Testing repository: ${{ github.repository }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Git SHA: ${{ github.sha }}" | tee -a $GITHUB_STEP_SUMMARY
          echo "Node.js version: $NODE_VERSION" | tee -a $GITHUB_STEP_SUMMARY
          echo "Hardhat version: $HARDHAT_VERSION"  | tee -a $GITHUB_STEP_SUMMARY
          echo "Forge version: $FORGE_VERSION" | tee -a $GITHUB_STEP_SUMMARY
          echo "" | tee -a $GITHUB_STEP_SUMMARY
          for file in **/*.result; do
            cat "$file" | tee -a $GITHUB_STEP_SUMMARY
            echo "" | tee -a $GITHUB_STEP_SUMMARY
          done
